# Generated by Django 4.1 on 2022-08-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
